In [12]:
import numpy as np

In [15]:
mat = np.array([[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]])
# y = np.array([1, -2, 4, 6]).reshape((4, 1))
# np.linalg.solve(mat, y)
# np.linalg.matrix_rank([[1, 1, -1, -1], [2, 5, -7, -5], [2, -1, 1, 3], [5, 2, -4, 2], [1, -2, 4, 6]])
np.linalg.inv(mat)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [26]:
mat_bT = np.array([[0, -1, 2, 0, 2], [1, -3, 1, -1, 2], [-3, 4, 1, 2, 1]])
mat_b = mat_bT.T
mat_c = mat_bT @ mat_b
mat_c

array([[  9,   9,   0],
       [  9,  16, -14],
       [  0, -14,  31]])

In [28]:
mat_cinv = np.linalg.inv(mat_c)
mat_cinv@mat_bT@np.array([[-1], [-9], [-1],[ 4], [1]])

array([[-3.],
       [ 4.],
       [ 1.]])

In [29]:
A = np.array([[1, 3, 5], [2, 4, 6], [0, 2, 4]])
np.linalg.det(A)

0.0

In [35]:
import numpy as np
sigma = np.array([[1.62, 0], [0, 1], [0, 0]])
U = np.array([[-0.79, 0, -0.62], [0.38, -0.78, -0.49], [-0.48, -0.62, 0.62]])
V = np.array([[-0.78, -0.62], [0.62, -0.78]])

In [37]:
A = U@sigma@V.T
print(np.linalg.det(A@A.T))
print(np.linalg.det(A.T@A))

5.854170587626052e-17
2.5652914700837477


In [32]:
np.linalg.det(sigma@sigma.T)

0.0

In [33]:
sigma.T@sigma

array([[2.6244, 0.    ],
       [0.    , 1.    ]])

In [34]:
1.62**2

2.6244000000000005

In [42]:
90/400

0.225